/* Generated by Together */

package edu.washington.java.course;

public class TestEncapsulation {
	public void publicMethod() {
          System.out.println("in TestEncapsulation.publicMethod");
        }
	protected int protectedInt;
	String packageString;
	private double privateDouble;
}
